### PR TITLE
Commander Whitelist

### PR DESCRIPTION
**Pull request by BroBeansCPG**
Add your steam ID's

### CODE REVIEW

**Comment by Grewsome2018** [comment]
Added and happy to merge once the boys have added theirs.

**Comment by Grewsome2018** [comment]
@McFurSun @Daffles add your Steam IDs to the whitelist file

**Comment by BroBeansCPG** [comment]
It’s an array, so can someone chuck commas after each different ID excluding the last one. 

Otherwise I’ll do it after everyone adds theirs. Cheers

**Comment by McFurSun** [comment]
I've added commas and mine and @Daffles UIDs.
although I'm not to sure if i did it to the right place.
https://github.com/BroBeansCPG/Liberation-Livonia/pull/2

**Comment by BroBeansCPG** [comment]
All good to go, just needs reviewing

**Review by the-pope-himself — APPROVED** [review]
Looks good.

**Review by Grewsome2018 — APPROVED** [review]

**Pull request merged**
