### PR TITLE
Update UCR_setup.sqf

### PR DESCRIPTION
**Pull request by Grewsome2018**
Reduce armed civ % to 40 from 70 and change debug to false. Also turn on racism because why not?

### CODE REVIEW

**Comment by the-pope-himself** [comment]
Agree with the 40%. Didn't think we'd need racism for the pending Liberation as all factions are Caucasian and most players will be too, unless they choose otherwise. It's an extra process that might reduce overall performance.

**Comment by BroBeansCPG** [comment]
Agree on leaving racism off. 

Higher armed civilian % benefits us more from my understanding. Where as less limits us to how many effective units we can recruit

**Comment by Grewsome2018** [comment]
Pls review, have removed racism because I forgot we weren't going up against the taliban again. Also, we aren't trying to start a civil war which is why I turned down armed civs

**Comment by the-pope-himself** [comment]
It also might be worth investigating exactly what happens to civs when they're recruited as it may come with unintended consequences...If they change to blufor for example we may end up with them triggering zones, effecting our reputation when killed by opfor etc...

**Comment by McFurSun** [comment]
Do we just turn off the recruit civ function for now and only use incognito as an infiltration mechanic?

**Comment by BroBeansCPG** [comment]
Until further testing is done, it's probably not a bad idea. 

@Grewsome2018 do you want to change that and then we can merge

**Review by Grewsome2018 — COMMENTED** [review]
And civ recruitment is now off...

**Pull request merged**
